### PR TITLE
Update to work with anime 3.0

### PR DESCRIPTION
**Pull request by laSinteZ**
### Description
This PR fixes current problem with vue-anime and animejs 3. I guess they've changed exports, so now it is required to import "default", otherwise you'll get an "anime is not a function" error.

screen shot 2019-01-23 at 20 21 24

### Possible drawbacks
I think it will stop working with old "anime" versions, so we need to release a "major" version.

### CODE REVIEW

**Comment by BenAHammond** [comment]
Just bump the minor version, we've already bumped the major version to map to the new release. I wasn't aware that they had changed their exports, thanks for submitting a fix.

**Comment by laSinteZ** [comment]
Done.
